### ISSUE TITLE
The rustr package

### ISSUE THREAD

**Issue by yihui** [r-rust/hellorust#1]
This is just FYI: @qinwf has worked on the rustr package for a couple of years: https://github.com/rustr/rustr

**Comment by jeroen** [comment]
This is also mentioned in the [readme](https://github.com/jeroen/hellorust#resources). I don't understand how to use `rustr` in R packages, or if it is intended to embed R in rust applications? 

This repository is meant as a *minimal example* for setting up portable R packages with rust code, as a template for R bindings to rust libraries.

Perhaps we could use `rustr` headers in R packages by importing `rustr` it in [Cargo.toml](https://github.com/jeroen/hellorust/blob/master/src/myrustlib/Cargo.toml) so that we can manipulate SEXP types in rust code? Maybe @qinwf can point us to an example of using `rustr` in R packages.

**Comment by yihui** [comment]
Ah, sorry I didn't read readme it carefully enough.
