### ISSUE TITLE
Rust and cargo on CRAN

### ISSUE THREAD

**Issue by nx10** [r-rust/hellorust#12]
Are there any updates or recommendations on Rust/cargo support on CRAN? I saw that gifski still downloads precompiled binaries on windows (for CRAN). 
I have been watching all R-Rust adjecient developments for the last years but am not sure whether to invest a lot of work into creating a rust port of one of my libraries is worth it. I would very much prefer working with rust instead of C/C++ and think there would be massive gains in productivity and safety, but I don't want to invest the initial bulk of work if it's something that will ultimately create a lot of friction with the CRAN team and infrastructure.

I am raising this question here as you seem to be the only dev that has maintained a Rust-R package on CRAN for a longer time.
If this is not the place to ask I will of course head over to the mailing list.

**Comment by eitsupi** [comment]
As you may know, binary installation is required for Windows as of August of this year, according to the following post by @yutannihilation.
https://stat.ethz.ch/pipermail/r-package-devel/2022q3/008291.html

**Comment by nx10** [comment]
@eitsupi I actually just found https://github.com/yutannihilation/string2path and the blogpost https://yutani.rbind.io/post/rust-and-cran-repository-policy/ shortly before your message. Thank you for linking the email thread!

I am wondering if we could avoid downloading any binaries by shipping compressed sources of all dependencies and just failing the build with an error message when rust is not installed.

**Comment by yutannihilation** [comment]
> I am wondering if we could avoid downloading any binaries by shipping compressed sources of all dependencies and just failing the build with an error message when rust is not installed.

I think that should be fine. The problem is that Rust installation on CRAN machines is incomplete. For example, it seems Win-builder has Rust installed, but CRAN build machines don't. Probably, the CRAN maintainers are interested in supporting Rust, but the current situation is unclear.

At the time of writing <https://yutani.rbind.io/post/rust-and-cran-repository-policy/>, I was expecting that my package will be removed from CRAN together with other Rust-R packages. However, the packages are still there for unknown reason. I mean, most of the packages are left unmodified, so the problem the CRAN maintainers got mad at us for should be unresolved, so I have no idea why the CRAN maintainers don't execute what they said. I and other package maintainers asked the CRAN maintainers, but we could get no response.

Maybe R-pkg-devel mailing list is the best place to ask, although it's not very likely to get the answer there.

**Comment by nx10** [comment]
@yutannihilation I did ask on the mailing list and it spawned a bit of a discussion (see the extended thread of https://stat.ethz.ch/pipermail/r-package-devel/2022q4/008638.html).

It seems like every CRAN machine (now) has the Rust compiler installed.

Edit: I will watch the mailing list further, but @yutannihilation if you want to collaborate, or if I can help with anything let me know. I would like to port the webserver part of https://github.com/nx10/httpgd to Rust as soon as I know it will not be deleted. (I can not risk it being deleted for a longer time as many VScode R users depend on it)

**Comment by eitsupi** [comment]
Since hellorust, which does not do binary downloads, has been registered on CRAN, perhaps we can submit packages to CRAN that uses Rust in the same way?
https://cran.r-project.org/package=hellorust

**Comment by jeroen** [comment]
Let's wait a few days for the check results on other platforms.

**Comment by nx10** [comment]
I am still a bit confused regarding to what CRAN wants us to do about cargo dependency copyright holders. Can we ignore these as they are provided by cargo or do we need a script that crawls the dependency tree and ads them all to the DESCRIPTION. 
Also CRAN not being notified if a dependency updates on cargo/crates.io.

**Comment by jeroen** [comment]
I think generally speaking, the description+license should list authorship of all the source code __that is contained within that source package on CRAN__. So if have copied any code or other material from others in the source package that you submit to CRAN, you should mention those authors, because CRAN hosts that material on their servers.

I don't think your package description file should name authors of 3rd party modules which your package depends on or links to, or even downloads, if that code is not included with the source package that is on hosted CRAN.

**Comment by nx10** [comment]
Thanks! That would certainly make things less complicated. 

I am guessing cargo dependencies updating falls into the same logic? (I.e.: Even if we fix all direct dependencies to specific versions, indirect dependencies may use wildcards)

**Comment by yutannihilation** [comment]
Wow, what a good news! I'll also try removing the fallback mechanism from my package.

One thing, my translation of the CRAN Repositlry policy is different on this point 

>even downloads

as the policy says (c.f. [my blog post](https://yutani.rbind.io/post/rust-and-cran-repository-policy/#doesnt-describe-the-authorship-and-copyright))

> ('All components' includes any downloaded at installation or during use.)

but I'm not sure how the CRAN people judge ¯\\_(ツ)\_/¯

**Comment by nx10** [comment]
> One thing, my translation of the CRAN Repositlry policy is different on this point
> 
> > even downloads
> 
> as the policy says (c.f. [my blog post](https://yutani.rbind.io/post/rust-and-cran-repository-policy/#doesnt-describe-the-authorship-and-copyright))
> 
> > ('All components' includes any downloaded at installation or during use.)
> 
> but I'm not sure how the CRAN people judge ¯\_(ツ)_/¯

I have been thinking about this, and one way to argue against this is that the dependencies are not downloaded by the R package, but by cargo which is not downloaded or shipped with the package.

But I agree an explicit verdict regarding this and the dependency update issue from CRAN would be good.

**Comment by jeroen** [comment]
> I have been thinking about this, and one way to argue against this is that the dependencies are not downloaded by the R package, but by cargo which is not downloaded or shipped with the package.

I agree with this. In theory, cargo could use dependencies from a local cache, or a local mirror, and not download anything. The same holds for tools like pandoc, which are used by many packages but may also download resources from the internet.

> But I agree an explicit verdict regarding this and the dependency update issue from CRAN would be good.

Please don't push too hard on this. As you can read on the mailing list, the cran maintainers don't use rust and they are [not interested](https://stat.ethz.ch/pipermail/r-package-devel/2022q4/008640.html) in learning how it works or explaining people how it should be done. They have done their part by installing the rustc toolchain on all CRAN machines, and approving the hellorust package. They [expect the package authors](https://stat.ethz.ch/pipermail/r-package-devel/2022q4/008640.html) to share best practices. So I think as long as you don't do things that are abusing their infrastructure, it is OK.

I would recommend to use strict versions in cargo lock files though. One thing that CRAN really does not like is if something stops working from one day to another, due to some uncontrolled external changes (i.e. new versions of cargo deps).

**Comment by nx10** [comment]
> I would recommend to use strict versions in cargo lock files though. One thing that CRAN really does not like is if something stops working from one day to another, due to some uncontrolled external changes (i.e. new versions of cargo deps).

A note for anyone following this thread: You might want to pass `--locked` and possibly `--frozen` to cargo to ensure the lockfile won't get updated: https://doc.rust-lang.org/cargo/commands/cargo-build.html#manifest-options

**Comment by jeroen** [comment]
I started a faq for R packages with rust code, with all the gotchas that I am aware of: https://github.com/r-rust/faq

If anyone else wants to add more things, let me know and I'll add you to the repo.

**Comment by yutannihilation** [comment]
Looks super useful! Thanks so much. I think I can add some more I learned from your code, which might be too obvious to you. I'll send one or two pull requests first so that you can decide whether or not I'm good enough to be added to the repo.

(Disclaimer: I'm a member of [extendr project](https://github.com/extendr/), but I'll do my best not to advertise it in the repo)

**Comment by eitsupi** [comment]
FYI, thanks to your advice I was able to submit [an R package](https://github.com/eitsupi/prqlr/tree/a76602e9809f9ffb6a04de87e359818e7680291c) to CRAN that uses cargo. (See also extendr/rextendr#233)

Downloading Rust packages from GitHub or crates.io works fine, it's just that the Rust version is a bit old (Debian testing, about 4 months behind?).

**Comment by jeroen** [comment]
Great, happy to see more rust packages appearing on cran!
