### ISSUE TITLE
Availability of rust/cargo in the R ecosystem

### ISSUE THREAD

**Issue by clauswilke** [r-rust/hellorust#6]
I'm seriously considering using Rust for an R package, but before I embark on this project I'd find it helpful if you could provide some clarifications of when and where I can assume `cargo` is available. I can use the template provided here to create an R package that I can build on my own machine, but can I then also submit this to CRAN? The gifski package is on CRAN, so I assume the answer is "yes", but I haven't been able to find any documentation that affirms this.

Also, related, if rust is generally available, which version(s) can I rely on? And can I assume it's available on all architectures CRAN supports, or only on some?

**Comment by jeroen** [comment]
I obviously cannot speak for CRAN. My experience is that rust / cargo is installed on the cran Linux check servers. The version they use is the one that ships with Fedora / Debian:

 - https://apps.fedoraproject.org/packages/rust
 - https://packages.debian.org/bullseye/cargo

The last time I checked, rust was also installed on the Mac builder, but I can't say this for sure because the server was cleaned recently. You would need to ask in `r-sig-mac`.

I'm quite sure cargo is __not__ available on the cran windows machines. You can easily test this yourself via the public winbuilder: https://win-builder.r-project.org/ 

As a workaround, for the CRAN version of gifski I am using [recompiled binaries](https://github.com/cran/gifski/blob/master/src/Makevars.win#L8-L9) from rwinlib.

**Comment by clauswilke** [comment]
Thanks for the information! You may want to add this to the README, since it's a major impediment to anybody who isn't in a position to provide recompiled windows binaries for their rust code.

**Comment by jeroen** [comment]
It will get there, we just need to be patient. 

Providing precompiled binaries is really easy, you can just store the binaries from an appveyor build of your R package and publish them on any webserver.
